/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.bll.CourseInstructorBUS;
import com.dto.CourseInstructorDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author PC
 */
public class CourseInstructorPN extends UIPanel {
    CourseInstructorBUS bus = new CourseInstructorBUS();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form CInstructor
     */
    public CourseInstructorPN() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        docDSCI();        
    }
    public void docDSCI() {
        CourseInstructorBUS bus = new CourseInstructorBUS();
        if(CourseInstructorBUS.dsci == null);
              bus.docSDCI();
              
        Vector header = new Vector();
        header.add("CourseID");
        header.add("PersonID");
        model = new DefaultTableModel(header, 0);
        for(CourseInstructorDTO ci : CourseInstructorBUS.dsci){
            Vector row = new Vector();
            row.add(ci.getCourseID());
            row.add(ci.getPersonID());
            model.addRow(row);
        }        
        tblCourseInstructor.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTK = new JTextField();
        btTimkiem = new JButton();
        cbCourseInstructor = new JComboBox<>();
        btThem = new JButton();
        btSua = new JButton();
        btXoa = new JButton();
        jScrollPane1 = new JScrollPane();
        tblCourseInstructor = new JTable();
        txCourseID = new JTextField();
        txPersonID = new JTextField();
        btDSCourseID = new JButton();
        btDSPersonID = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        inputTK.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        btTimkiem.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btTimkiem.setIcon(new ImageIcon(getClass().getResource("/icon/icons8-search-24.png"))); // NOI18N
        btTimkiem.setText("Search");
        btTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimkiemActionPerformed(evt);
            }
        });

        cbCourseInstructor.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cbCourseInstructor.setModel(new DefaultComboBoxModel<>(new String[] { "CourseID", "PersonID", "ALL" }));

        btThem.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btThem.setIcon(new ImageIcon(getClass().getResource("/icon/icons8-plus-24.png"))); // NOI18N
        btThem.setText("Add");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btSua.setIcon(new ImageIcon(getClass().getResource("/icon/icons8-update-24.png"))); // NOI18N
        btSua.setText("Update");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btXoa.setIcon(new ImageIcon(getClass().getResource("/icon/icons8-delete-24.png"))); // NOI18N
        btXoa.setText("Delete");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        tblCourseInstructor.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCourseInstructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseInstructorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourseInstructor);

        txCourseID.setEnabled(false);
        txCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCourseIDActionPerformed(evt);
            }
        });

        txPersonID.setEnabled(false);
        txPersonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPersonIDActionPerformed(evt);
            }
        });

        btDSCourseID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btDSCourseID.setText("...");
        btDSCourseID.setMinimumSize(new java.awt.Dimension(40, 28));
        btDSCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDSCourseIDActionPerformed(evt);
            }
        });

        btDSPersonID.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btDSPersonID.setText("...");
        btDSPersonID.setPreferredSize(new java.awt.Dimension(40, 28));
        btDSPersonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDSPersonIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("CourseID");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("PersonID");

        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txCourseID, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                            .addComponent(btThem, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSua)
                                .addGap(51, 51, 51)
                                .addComponent(btXoa))
                            .addComponent(btDSCourseID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCourseInstructor, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputTK, GroupLayout.PREFERRED_SIZE, 274, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTimkiem))
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txPersonID, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDSPersonID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimkiem, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCourseInstructor)
                    .addComponent(inputTK))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btDSPersonID, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txPersonID)
                    .addComponent(txCourseID)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btDSCourseID, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 340, GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCourseIDActionPerformed

    private void btDSCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDSCourseIDActionPerformed
        // TODO add your handling code here:
        DSCourseID dsci = new DSCourseID();
        dsci.setVisible(true);
    }//GEN-LAST:event_btDSCourseIDActionPerformed

    private void btDSPersonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDSPersonIDActionPerformed
        // TODO add your handling code here:
        DSPersonID dspi = new DSPersonID();
        dspi.setVisible(true);
    }//GEN-LAST:event_btDSPersonIDActionPerformed

    private void txPersonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPersonIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPersonIDActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        if(txCourseID.getText().trim().compareTo("") != 0
            && txPersonID.getText().trim().compareTo("") !=0){
        
            int courseid = Integer.parseInt(txCourseID.getText());
            int personid = Integer.parseInt(txPersonID.getText());
            CourseInstructorDTO ci = new CourseInstructorDTO(courseid, personid);
            bus.them(ci);
            this.docDSCI();
       }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        if(txCourseID.getText().trim().compareTo("") != 0
            && txPersonID.getText().trim().compareTo("") !=0){
        
            int courseid = Integer.parseInt(txCourseID.getText());
            int personid = Integer.parseInt(txPersonID.getText());
            CourseInstructorDTO ci = new CourseInstructorDTO(courseid, personid);
            bus.sua(ci);
            this.docDSCI();
       }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        if(txCourseID.getText().trim().compareTo("") != 0
            && txPersonID.getText().trim().compareTo("") !=0){
        
            int courseid = Integer.parseInt(txCourseID.getText());
            int personid = Integer.parseInt(txPersonID.getText());
            CourseInstructorDTO ci = new CourseInstructorDTO(courseid, personid);
            bus.xoa(ci);
            this.docDSCI();
       }else{
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tblCourseInstructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseInstructorMouseClicked
        // TODO add your handling code here:
        int index = tblCourseInstructor.getSelectedRow();
        txCourseID.setText(model.getValueAt(index, 0).toString());
        txPersonID.setText(model.getValueAt(index, 1).toString());
        
    }//GEN-LAST:event_tblCourseInstructorMouseClicked

    private void btTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimkiemActionPerformed
        // TODO add your handling code here:
        int index = cbCourseInstructor.getSelectedIndex();
        String in = inputTK.getText();
        if(index == 0)
            tblCourseInstructor.setModel(ketQuaTimKiem(bus.timTheoCourseID(Integer.parseInt(in))));
        else if (index == 1)
            tblCourseInstructor.setModel(ketQuaTimKiem(bus.timTheoPersonID(Integer.parseInt(in))));
        else
            tblCourseInstructor.setModel(ketQuaTimKiem(bus.timTheoTatCa(Integer.parseInt(in))));
    }//GEN-LAST:event_btTimkiemActionPerformed

    private DefaultTableModel ketQuaTimKiem(ArrayList<CourseInstructorDTO> rs){
        Vector header = new Vector();
        header.add("CourseID");
        header.add("PersonID");
        model = new DefaultTableModel(header, 0);
        for(CourseInstructorDTO ci : rs){
            Vector row = new Vector();
            row.add(ci.getCourseID());
            row.add(ci.getPersonID());
            model.addRow(row);
        }
        return model;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btDSCourseID;
    private JButton btDSPersonID;
    private JButton btSua;
    private JButton btThem;
    private JButton btTimkiem;
    private JButton btXoa;
    private JComboBox<String> cbCourseInstructor;
    private JTextField inputTK;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JScrollPane jScrollPane1;
    private JTable tblCourseInstructor;
    public static JTextField txCourseID;
    public static JTextField txPersonID;
    // End of variables declaration//GEN-END:variables

    void setBackground(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public UIPanel newView() {
        return this;
    }
}
